on: [push]
name: build
jobs:
  runhaskell:
    name: Build & Test
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    defaults:
      run:
        working-directory: ./soundness-checker
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - run: cd soundness-checker && stack test