on: [push]
name: build
jobs:
  runhaskell:
    name: Build & Test
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - run: echo `pwd` && ls && cd ./Master/soundness-checker && stack test